---
title: "| Turismo con enfoque en Puerto Plata"
format: 
  dashboard:
    orientation: columns
    logo: logo.png
    theme:
      - custom.scss
---

## Column {width=60%}

```{r setup}
library(dplyr)
library(reactable)
library(htmltools)
library(shiny)
library(highcharter)

llegadas <- readRDS(here::here("data/llegadas.rds"))
countries <- readRDS(here::here("data/countries_code.rds"))
llegadas_2024 <- readRDS(here::here("data/llegadas_2024.rds"))

source(here::here("R/functions/ratings_table.R"))
source(here::here("R/functions/get_data_turismo.R"))
```

```{r}
#| title: Visitantes según país de residencia

map_countries <- "custom/world-lowres"
map_data <- get_data_from_map(download_map_data(map_countries))

llegadas_by_country <- llegadas_2024 |>
  summarise(
    llegadas = sum(sexo_total),
    .by = pais_status
  )  |>
  rename(country = pais_status) |>
  right_join(countries) |>
  right_join(map_data) |>
  select(code = `hc-a2`, country, llegadas) |>
  mutate(
    llegadas_log = log(llegadas),
    llegadas_label = scales::comma(llegadas)
  )

hcmap(
  map_countries,
  data = llegadas_by_country,
  value = "llegadas_log",
  joinBy = c("hc-a2", "code"),
  name = "Llegadas",
  dataLabels = list(enabled = FALSE),
  borderColor = "#FAFAFA",
  borderWidth = 0.1,
  tooltip = list(pointFormat = "{point.country} {point.llegadas_label}")
)
```


```{r}
#| title: Distribución según aeropuerto

llegadas |>
  filter(year == 2024, nacionalidad == "Total") |>
  summarise(
    llegadas = round(sum(llegadas)),
    .by = aeropuerto
  ) |>
  mutate(
    aeropuerto = forcats::fct_reorder(aeropuerto, llegadas)
  ) |>
  arrange(desc(llegadas)) |>
  hchart("bar", hcaes(x = aeropuerto, y = llegadas)) |>
  hc_xAxis(title = list(text = NA)) |> 
  hc_yAxis(title = list(text = NA))
```

## Column {width=40%}

```{r data}
#| title: Rating se los destinos

rating_data <- tibble::tribble(
  ~stars, ~puerto_plata, ~punta_cana,
      1L,            0L,          0L,
      2L,            4L,          3L,
      3L,           55L,         96L,
      4L,           52L,         47L,
      5L,            7L,         50L
  )

ratings_table(rating_data)
```

```{r}
#| title: Llegadas aéreas totales

llegadas |>
  filter(year > 2010, nacionalidad == "Total") |>
  summarise(
    llegadas = round(sum(llegadas)),
    .by = c(year)
  ) |>
  hchart("column", hcaes(x = year, y = llegadas)) |> 
  hc_xAxis(title = list(text = NULL)) |> 
  hc_yAxis(title = list(text = "Millones")) |>
  hc_tooltip(
    pointFormat ="Llegadas: {point.y}"
  )
```

```{r}
#| title: Visitantes según sexo

llegadas_2024 |>
  filter(aeropuerto == "Todos", categoria_region == "TOTAL") |>
  select(year, Masculino = sexo_masculino, Femenino = sexo_femenino) |>
  summarise(across(-year, \(x) round(sum(x)))) |> 
  tidyr::pivot_longer(
    everything(),
    names_to = "Sexo",
    values_to = "Llegadas"
  ) |>
  hchart("pie", hcaes(x = Sexo, y = Llegadas))

```
