---
execute:
  echo: false
  warning: false
  message: false
---

```{r setup}
library(dplyr)
library(reactable)
library(htmltools)
library(shiny)
library(highcharter)
library(echarts4r)
```

```{r data}
llegadas <- readRDS(here::here("data/llegadas.rds"))

star_stats <- tibble::tribble(
  ~stars, ~puerto_plata, ~punta_cana,
      1L,            0L,          0L,
      2L,            4L,          3L,
      3L,           55L,         96L,
      4L,           52L,         47L,
      5L,            7L,         50L
  )
```

```{r stars_table}

rating_stars <- function(rating, max_rating = 5) {
  star_icon <- function(empty = FALSE) {
    tagAppendAttributes(
      shiny::icon("star"),
      style = paste("color:", if (empty) "#edf0f2" else "orange"),
      "aria-hidden" = "true"
    )
  }

  rounded_rating <- floor(rating + 0.5)  # always round up
  stars <- lapply(seq_len(max_rating), function(i) {
    if (i <= rounded_rating) star_icon() else star_icon(empty = TRUE)
  })

  label <- sprintf("%s out of %s stars", rating, max_rating)
  div(title = label, role = "img", stars)
}

star_stats |>
  reactable(
    highlight = TRUE,
    class = "bergatin-table",
    defaultColDef = colDef(headerClass = "header"),
    columns = list(
      stars = colDef(
        name = "Puntuación", cell = function(value) rating_stars(value),
        align = "center"
      ),
      puerto_plata = colDef(
        name = "Puerto Plata",
        align = "left",
        cell = \(value) {
          width <- paste0(value * 100 / max(star_stats$puerto_plata), "%")
          value <- scales::percent(value / sum(star_stats$puerto_plata), accuracy = 0.1)
          value <- format(value, width = 6, justify = "right")
          bar <- div(
            class = "bar-chart",
            style = list(marginRight = "0.375rem"),
            div(class = "bar", style = list(width = width, backgroundColor = "orange"))
          )
          div(class = "bar-cell", span(class = "number", value), bar)
        }
      ),
      punta_cana   = colDef(
        name = "Punta Cana",
        align = "left",
        cell = \(value) {
          width <- paste0(value * 100 / max(star_stats$punta_cana), "%")
          value <- scales::percent(value / sum(star_stats$punta_cana), accuracy = 0.1)
          value <- format(value, width = 5, justify = "right")
          bar <- div(
            class = "bar-chart",
            style = list(marginRight = "0.375rem"),
            div(class = "bar", style = list(width = width, backgroundColor = "gray"))
          )
          div(class = "bar-cell", span(class = "number", value), bar)
        }
      )
    )
  )
```


```{r}
llegadas |>
  filter(residencia == "Total", year > 2013) |>
  summarise(
    llegadas = sum(llegadas, na.rm = TRUE),
    .by = year
  ) |>
  e_chart(year) |>
  e_bar(llegadas) |>
  e_grid(left = "15%") |>
  e_legend(show = FALSE) |>
  e_tooltip() |>
  e_title("Llegadas aéreas")
```

```{r}
llegadas |>
  filter(year == 2024, nacionalidad == "Total") |>
    summarise(
  llegadas = sum(llegadas),
  .by = aeropuerto
  ) |>
  arrange(llegadas) |>
  e_chart(aeropuerto) |>
  e_bar(llegadas) |>
  e_flip_coords() |>
  e_legend(show = FALSE) |>
  e_tooltip() |>
  e_grid(left = "25%") |>
  e_title("Llegadas aéreas 2024, según aeropuerto")
```

